// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbxowcfafuwkzxeaspvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieG93Y2ZhZnV3a3p4ZWFzcHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTU4NTEsImV4cCI6MjA3MzU3MTg1MX0.tMR6wSNdaGM5Epvu5h2HiAY00kodUwbnwEGaqjPKQsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});